### ISSUE TITLE
Recommendation: More code comments

### ISSUE THREAD

**Issue by melissamcewen** [DarryllRobinson/bapi-p3-the-scoop#4]
I think adding in comments to understand the workflow would be very valuable when understanding and debugging. My general practice is to use console.log when debugging and then everything I remove a console.log, replace it with a comment that explains what happens when the function is run.

**Comment by DarryllRobinson** [comment]
Morning Melissa

 

I apologise for not responding yet – last week was a particularly tough one at work. Thank you for the review and advice – I like the one about the console.log output becoming the comments!

 

Have a great day

 

Darryll
